name: RedTieCinema
favicon: null
layout_spectrum: 0.6838250239379704
typography_spectrum: 0.5852024178020656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1605782622937113
  lightness: 0.2063142852857709
  saturation: 0.8871762950439006
  rhythmicContrast: 0.5741777860093862
purpose: []
